
# cxa is for memory management
# rtti is run time identification
# leading_underscore has something to do with the naming inside output
GPPPARAMS = -m32 -fno-use-cxa-atexist -nostdlib -fno-builtin -fno-rtti -fno-exceptions -fno-leading-underscore
ASPARAMS  = --32
LDPARAMS  = -melf_i386

objects   = loader.o kernal.o

%.o: %.cpp
    g++ ${GPPPARAMS} -o $@ -c $<

%.o: %.s
    as ${ASPARAMS} -o $@ $<

mykernal.bin: linker.ld
    ld ${LDPARAMS} -T $< -o $@ ${objects}

install: mykernal.bin
    sudo cp $< /boot/mykernal.bin

debug:
    @echo ${ASPARAMS}
